"
struct GdkEventMotion

Generated when the pointer moves.
"
Class {
	#name : #GdkEventMotion,
	#superclass : #GdkEvent,
	#traits : 'TGdkEventState',
	#classTraits : 'TGdkEventState classTrait',
	#classVars : [
		'OFFSET_AXES',
		'OFFSET_DEVICE',
		'OFFSET_IS_HINT',
		'OFFSET_SEND_EVENT',
		'OFFSET_STATE',
		'OFFSET_TIME',
		'OFFSET_TYPE',
		'OFFSET_WINDOW',
		'OFFSET_X',
		'OFFSET_X_ROOT',
		'OFFSET_Y',
		'OFFSET_Y_ROOT'
	],
	#category : #'Gtk-Base-Events'
}
