"
Defines the position and size of a rectangle. It is identical to cairo_rectangle_int_t.

https://developer.gnome.org/gdk3/stable/gdk3-Points-Rectangles-and-Regions.html#GdkRectangle
"
Class {
	#name : #GdkRectangle,
	#superclass : #GtkStructure,
	#traits : 'TGtkLibrary',
	#classTraits : 'TGtkLibrary classTrait',
	#classVars : [
		'OFFSET_HEIGHT',
		'OFFSET_WIDTH',
		'OFFSET_X',
		'OFFSET_Y'
	],
	#pools : [
		'GtkTypes'
	],
	#category : #'Gtk-Misc'
}
