"
Definition of basic tyles from glib

https://github.com/GNOME/glib/blob/cbfa776fc149fcc3e351fbdf68c1a299519f4905/gobject/gtype.h
"
Class {
	#name : #GType,
	#superclass : #SharedPool,
	#traits : 'TGtkLibrary',
	#classTraits : 'TGtkLibrary classTrait',
	#classVars : [
		'G_TYPE_BOOLEAN',
		'G_TYPE_BOXED',
		'G_TYPE_CHAR',
		'G_TYPE_DOUBLE',
		'G_TYPE_ENUM',
		'G_TYPE_FLAGS',
		'G_TYPE_FLOAT',
		'G_TYPE_FUNDAMENTAL_SHIFT',
		'G_TYPE_INT',
		'G_TYPE_INT64',
		'G_TYPE_INTERFACE',
		'G_TYPE_INVALID',
		'G_TYPE_LONG',
		'G_TYPE_NONE',
		'G_TYPE_OBJECT',
		'G_TYPE_PARAM',
		'G_TYPE_POINTER',
		'G_TYPE_STRING',
		'G_TYPE_UCHAR',
		'G_TYPE_UINT',
		'G_TYPE_UINT64',
		'G_TYPE_ULONG',
		'G_TYPE_VARIANT'
	],
	#pools : [
		'GtkTypes'
	],
	#category : #'Gtk-Misc'
}
