Trait {
	#name : 'GtkSourceViewTLibrary',
	#traits : 'TEmpty',
	#classTraits : 'TEmpty classTrait',
	#category : 'GtkSourceView-Base',
	#package : 'GtkSourceView',
	#tag : 'Base'
}

{ #category : 'library path' }
GtkSourceViewTLibrary classSide >> ffiLibraryName [

	^ GtkSourceViewLibrary
]

{ #category : 'library path' }
GtkSourceViewTLibrary >> ffiLibraryName [

	^ GtkSourceViewLibrary
]
