"
https://developer.gnome.org/gtksourceview/stable/GtkSourceStyleScheme.html
"
Class {
	#name : 'GtkSourceStyleScheme',
	#superclass : 'GObject',
	#category : 'GtkSourceView-Style',
	#package : 'GtkSourceView',
	#tag : 'Style'
}

{ #category : 'instance creation' }
GtkSourceStyleScheme class >> new [

	self error: 'This can''t be made. You need to access languages through GtkSourceLanguageManager'
]
